import { useState, useCallback } from "react";
import * as ImagePicker from "expo-image-picker";
import * as FileSystem from "expo-file-system";
import * as MediaLibrary from "expo-media-library";
import {
  encryptImage,
  decryptImage,
  generateEncryptedThumbnail,
} from "../services/encryption";
import { VAULT_EXTENSION } from "../services/storage";
import { capturePhoto } from "../services/SecureCameraService";
import { useVault, useAuth } from "./useAuth";
import type { VaultFile } from "../services/storage";

export type OperationStatus = "idle" | "running" | "success" | "error";

function normaliseDisplayName(
  raw: string | null | undefined,
): string | undefined {
  if (!raw) return undefined;
  const basename = raw.split("/").pop() ?? raw;
  const noExt = basename.replace(/\.[^.]+$/, "");
  const trimmed = noExt.trim().slice(0, 80);
  return trimmed.length > 0 ? trimmed : undefined;
}

const AUTOGENERATED_PREFIX =
  /^(IMG|VID|DSC|DCIM|MVI|MOV|REC|PXL|MVIMG|PANO)[\-_]?[\d\-_]+$/i;
const NUMERIC_ONLY = /^[\d_\-\.]+$/;
const UUID_PATTERN =
  /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
const HEX_BLOB = /^[0-9a-f]{16,}$/i;
const TOO_SHORT = 3;

function isAutogenerated(name: string): boolean {
  if (NUMERIC_ONLY.test(name)) return true;
  if (name.length <= TOO_SHORT) return true;
  if (AUTOGENERATED_PREFIX.test(name)) return true;
  if (UUID_PATTERN.test(name)) return true; // 8c759663-f141-48b7-ac3f-ff82942d1e06
  if (HEX_BLOB.test(name)) return true; // long hex strings without separators
  return false;
}

function extractBasename(raw: string): string {
  return (raw.split("/").pop() ?? raw).replace(/\.[^.]+$/, "").trim();
}

function buildDisplayName(
  fileName: string | null | undefined,
  uri: string,
  importedAt: Date,
): string {
  // Try fileName first
  const fromFileName = fileName ? extractBasename(fileName) : "";
  if (fromFileName.length > TOO_SHORT && !isAutogenerated(fromFileName)) {
    return fromFileName.slice(0, 80);
  }

  // Try URI basename as secondary source
  const fromUri = extractBasename(uri);
  if (fromUri.length > TOO_SHORT && !isAutogenerated(fromUri)) {
    return fromUri.slice(0, 80);
  }

  // Both autogenerated — use import timestamp
  const d = importedAt;
  return `Photo ${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(d.getDate()).padStart(2, "0")} ${String(d.getHours()).padStart(2, "0")}-${String(d.getMinutes()).padStart(2, "0")}`;
}

interface VaultOperation {
  status: OperationStatus;
  progress: number;
  message: string;
  error: string | null;
}

const idle: VaultOperation = {
  status: "idle",
  progress: 0,
  message: "",
  error: null,
};

export function useVaultOperations() {
  const vault = useVault();
  const { suppressBackgroundLock, resumeBackgroundLock } = useAuth();

  const [encryptOp, setEncryptOp] = useState<VaultOperation>(idle);
  const [decryptOp, setDecryptOp] = useState<VaultOperation>(idle);

  // ── Pick images from gallery ─────────────────────────────────────────────

  const pickImages = useCallback(async (): Promise<
    ImagePicker.ImagePickerAsset[]
  > => {
    suppressBackgroundLock();
    const { status } = await ImagePicker.requestMediaLibraryPermissionsAsync();
    if (status !== "granted")
      throw new Error("Photo library permission denied");
    let result: ImagePicker.ImagePickerResult;
    try {
      result = await ImagePicker.launchImageLibraryAsync({
        mediaTypes: ["images"],
        allowsMultipleSelection: true,
        quality: 1,
        selectionLimit: 20,
      });
    } finally {
      resumeBackgroundLock();
    }

    if (result.canceled) return [];
    return result.assets;
  }, []);

  // ── Encrypt ──────────────────────────────────────────────────────────────

  const encryptImages = useCallback(
    async (
      assets: ImagePicker.ImagePickerAsset[],
      passcode: string,
      deleteOriginal: boolean,
      albumName?: string | null,
    ) => {
      setEncryptOp({
        status: "running",
        progress: 0,
        message: "Preparing vault...",
        error: null,
      });

      try {
        const outDir = await vault.ensureAlbumDir(albumName ?? null);
        const total = assets.length;

        for (let i = 0; i < total; i++) {
          const asset = assets[i];
          setEncryptOp({
            status: "running",
            progress: (i + 0.5) / total,
            message: `Encrypting ${i + 1} of ${total}...`,
            error: null,
          });

          const outPath = await encryptImage(asset.uri, passcode, outDir);
          const displayName = buildDisplayName(
            asset.fileName,
            asset.uri,
            new Date(),
          );

          // console.log("displayName: " + displayName);

          // Best-effort — a failed/missing thumbnail must never block the
          // primary encrypt; the grid falls back to the placeholder icon.
          const hasThumb = await generateEncryptedThumbnail(
            asset.uri,
            passcode,
            outPath,
          );

          // Awaited — must not run concurrently; each call does read→modify→write
          // on the index and concurrent calls would overwrite each other. The
          // thumbnail flag is folded into this same call rather than a second
          // index write, for the same reason.
          await vault.recordEncryptedFile(
            outPath,
            albumName ?? null,
            displayName,
            hasThumb,
          );

          if (deleteOriginal) {
            await FileSystem.deleteAsync(asset.uri, { idempotent: true });
          }
        }

        await vault.logActivity({
          type: "encrypt",
          fileCount: total,
          timestamp: Date.now(),
          detail: albumName ?? undefined,
        });

        setEncryptOp({
          status: "success",
          progress: 1,
          message: `${total} image${total !== 1 ? "s" : ""} encrypted`,
          error: null,
        });
      } catch (e: any) {
        setEncryptOp({
          status: "error",
          progress: 0,
          message: "",
          error: e.message ?? "Encryption failed",
        });
      }
    },
    [vault],
  );

  // ── Decrypt to Photos library ─────────────────────────────────────────────

  const decryptToLibrary = useCallback(
    async (uris: string[], passcode: string) => {
      setDecryptOp({
        status: "running",
        progress: 0,
        message: "Unlocking files...",
        error: null,
      });

      try {
        const { status } = await MediaLibrary.requestPermissionsAsync();
        if (status !== "granted")
          throw new Error("Media library permission denied");

        const cacheDir = FileSystem.cacheDirectory!;
        const total = uris.length;

        for (let i = 0; i < total; i++) {
          setDecryptOp({
            status: "running",
            progress: (i + 0.5) / total,
            message: `Decrypting ${i + 1} of ${total}...`,
            error: null,
          });

          const outPath = await decryptImage(uris[i], passcode, cacheDir);
          await MediaLibrary.saveToLibraryAsync(outPath);
          await FileSystem.deleteAsync(outPath, { idempotent: true });
        }

        await vault.logActivity({
          type: "decrypt",
          fileCount: total,
          timestamp: Date.now(),
        });

        setDecryptOp({
          status: "success",
          progress: 1,
          message: `${total} image${total !== 1 ? "s" : ""} saved to Photos`,
          error: null,
        });
      } catch (e: any) {
        const msg = e.message ?? "";
        const isWrongPasscode =
          msg.includes("padding") || msg.includes("passcode");
        setDecryptOp({
          status: "error",
          progress: 0,
          message: "",
          error: isWrongPasscode ? "Incorrect passcode" : "Decryption failed",
        });
      }
    },
    [vault],
  );

  // ── Secure Camera ────────────────────────────────────────────────────────

  /**
   * Capture a photo via the native camera, encrypt it immediately into the
   * active vault, then delete the temp camera file.
   *
   * The photo is never saved to the device gallery.
   * Returns true if a photo was captured and encrypted, false if the user
   * cancelled or permission was denied.
   */
  const captureAndEncrypt = useCallback(
    async (passcode: string, albumName?: string | null): Promise<boolean> => {
      suppressBackgroundLock();
      let tempUri: string | null;
      try {
        tempUri = await capturePhoto();
      } finally {
        resumeBackgroundLock();
      }
      if (!tempUri) return false;

      setEncryptOp({
        status: "running",
        progress: 0.3,
        message: "Encrypting photo...",
        error: null,
      });

      try {
        const outDir = await vault.ensureAlbumDir(albumName ?? null);
        const outPath = await encryptImage(tempUri, passcode, outDir);

        // Thumbnail is generated from the temp camera file before it's
        // deleted — best-effort, never blocks the primary encrypt.
        const hasThumb = await generateEncryptedThumbnail(
          tempUri,
          passcode,
          outPath,
        );

        // Always delete the temp camera file — it must never persist unencrypted
        await FileSystem.deleteAsync(tempUri, { idempotent: true });

        const now = new Date();
        const cameraDisplayName = `Photo ${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, "0")}-${String(now.getDate()).padStart(2, "0")} ${String(now.getHours()).padStart(2, "0")}-${String(now.getMinutes()).padStart(2, "0")}`;

        // Awaited for consistency with encryptImages — index write must complete
        // before we return so the caller's subsequent loadFiles() sees the entry.
        await vault.recordEncryptedFile(
          outPath,
          albumName ?? null,
          cameraDisplayName,
          hasThumb,
        );

        await vault.logActivity({
          type: "encrypt",
          fileCount: 1,
          timestamp: Date.now(),
          detail: albumName ?? undefined,
        });

        setEncryptOp({
          status: "success",
          progress: 1,
          message: "Photo encrypted",
          error: null,
        });

        return true;
      } catch (e: any) {
        // Best-effort cleanup on failure — temp file must not linger
        await FileSystem.deleteAsync(tempUri, { idempotent: true });

        setEncryptOp({
          status: "error",
          progress: 0,
          message: "",
          error: e.message ?? "Encryption failed",
        });

        return false;
      }
    },
    [vault],
  );

  const resetEncrypt = useCallback(() => setEncryptOp(idle), []);
  const resetDecrypt = useCallback(() => setDecryptOp(idle), []);

  return {
    encryptOp,
    decryptOp,
    pickImages,
    encryptImages,
    captureAndEncrypt,
    decryptToLibrary,
    resetEncrypt,
    resetDecrypt,
  };
}
