import { useState, useCallback } from "react";
import { Platform } from "react-native";
import * as ImagePicker from "expo-image-picker";
import * as FileSystem from "expo-file-system";
import * as MediaLibrary from "expo-media-library";
import {
  encryptImage,
  decryptImage,
  generateEncryptedThumbnail,
} from "../services/encryption";
import { capturePhoto } from "../services/SecureCameraService";
import {
  pickImagesNative,
  requestDeleteNative,
} from "../modules/media-store-resolver";
import { useVault, useAuth } from "./useAuth";

export type OperationStatus = "idle" | "running" | "success" | "error";

const AUTOGENERATED_PREFIX =
  /^(IMG|VID|DSC|DCIM|MVI|MOV|REC|PXL|MVIMG|PANO)[\-_]?[\d\-_]+$/i;
const NUMERIC_ONLY = /^[\d_\-\.]+$/;
const UUID_PATTERN =
  /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
const HEX_BLOB = /^[0-9a-f]{16,}$/i;
const TOO_SHORT = 3;

function isAutogenerated(name: string): boolean {
  if (NUMERIC_ONLY.test(name)) return true;
  if (name.length <= TOO_SHORT) return true;
  if (AUTOGENERATED_PREFIX.test(name)) return true;
  if (UUID_PATTERN.test(name)) return true; // 8c759663-f141-48b7-ac3f-ff82942d1e06
  if (HEX_BLOB.test(name)) return true; // long hex strings without separators
  return false;
}

function extractBasename(raw: string): string {
  return (raw.split("/").pop() ?? raw).replace(/\.[^.]+$/, "").trim();
}

function buildDisplayName(
  fileName: string | null | undefined,
  uri: string,
  importedAt: Date,
): string {
  // Try fileName first
  const fromFileName = fileName ? extractBasename(fileName) : "";
  if (fromFileName.length > TOO_SHORT && !isAutogenerated(fromFileName)) {
    return fromFileName.slice(0, 80);
  }

  // Try URI basename as secondary source
  const fromUri = extractBasename(uri);
  if (fromUri.length > TOO_SHORT && !isAutogenerated(fromUri)) {
    return fromUri.slice(0, 80);
  }

  // Both autogenerated — use import timestamp
  const d = importedAt;
  return `Photo ${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(d.getDate()).padStart(2, "0")} ${String(d.getHours()).padStart(2, "0")}-${String(d.getMinutes()).padStart(2, "0")}`;
}

// ── Picked asset (platform-normalized) ──────────────────────────────────────
//
// Android picks via modules/media-store-resolver (our own local native
// picker using Intent.ACTION_OPEN_DOCUMENT — see MediaStoreResolverModule.kt
// for why expo-image-picker isn't used here) and returns the original SAF
// document Uri with a persistable permission grant already taken; identity
// resolution for deletion (deleteDocument, or MediaStore translation as a
// fallback) happens natively inside requestDeleteNative, not here.
// iOS keeps using expo-image-picker + expo-media-library exactly as
// before; deletionRef is filled in from assetId, verified the same way it
// always was.
//
// deletionRef is the ONLY thing encryptImages trusts for deletion — null
// always means "no positively identified local original," never a guess to
// fall back on.
export interface PickedAsset {
  uri: string;
  fileName: string | null;
  deletionRef: string | null;
}

async function verifyIosAssetId(
  assetId: string | null | undefined,
): Promise<string | null> {
  if (!assetId) return null;
  try {
    const info = await MediaLibrary.getAssetInfoAsync(assetId);
    return info?.id ? assetId : null;
  } catch {
    return null;
  }
}

interface VaultOperation {
  status: OperationStatus;
  progress: number;
  message: string;
  error: string | null;
}

const idle: VaultOperation = {
  status: "idle",
  progress: 0,
  message: "",
  error: null,
};

export function useVaultOperations() {
  const vault = useVault();
  const { suppressBackgroundLock, resumeBackgroundLock } = useAuth();

  const [encryptOp, setEncryptOp] = useState<VaultOperation>(idle);
  const [decryptOp, setDecryptOp] = useState<VaultOperation>(idle);

  // ── Pick images from gallery ─────────────────────────────────────────────
  //
  // Android: our own local native picker (modules/media-store-resolver),
  // using Intent.ACTION_OPEN_DOCUMENT — returns the original document Uri
  // with a persistable permission grant, not expo-image-picker's
  // unreliable assetId. Deletion identity is resolved later, in
  // requestDeleteNative.
  // iOS: unchanged, still expo-image-picker + expo-media-library.

  const pickImages = useCallback(async (): Promise<PickedAsset[]> => {
    suppressBackgroundLock();
    try {
      if (Platform.OS === "android") {
        // Best-effort — denial doesn't block picking, it just means every
        // asset comes back with deletionRef: null (encryptImages will
        // simply never queue anything for deletion).
        await MediaLibrary.requestPermissionsAsync();

        const picked = await pickImagesNative(20);
        return picked.map((p) => ({
          uri: p.uri,
          fileName: p.fileName,
          deletionRef: p.documentUri,
        }));
      }

      // iOS
      const { status } = await ImagePicker.requestMediaLibraryPermissionsAsync();
      if (status !== "granted")
        throw new Error("Photo library permission denied");

      const result = await ImagePicker.launchImageLibraryAsync({
        mediaTypes: ["images"],
        allowsMultipleSelection: true,
        quality: 1,
        selectionLimit: 20,
      });
      if (result.canceled) return [];

      const assets: PickedAsset[] = [];
      for (const a of result.assets) {
        assets.push({
          uri: a.uri,
          fileName: a.fileName ?? null,
          deletionRef: await verifyIosAssetId(a.assetId),
        });
      }
      return assets;
    } finally {
      resumeBackgroundLock();
    }
  }, []);

  // ── Encrypt ──────────────────────────────────────────────────────────────

  const encryptImages = useCallback(
    async (
      assets: PickedAsset[],
      passcode: string,
      deleteOriginal: boolean,
      albumName?: string | null,
    ) => {
      setEncryptOp({
        status: "running",
        progress: 0,
        message: "Preparing vault...",
        error: null,
      });

      try {
        const outDir = await vault.ensureAlbumDir(albumName ?? null);
        const total = assets.length;

        // Collected as each asset is verified encrypted+recorded, then
        // deleted in ONE batched call after the loop — not per-asset. On
        // Android, requestDeleteNative tries DocumentsContract.deleteDocument
        // per Uri first (no dialog needed there) and only falls back to
        // MediaStore.createDeleteRequest — which surfaces a single OS
        // confirmation dialog for the whole fallback batch — for Uris that
        // don't support direct deletion; calling it once per asset would
        // mean up to `total` separate interruptions during a multi-photo
        // import.
        const assetIdsToDelete: string[] = [];

        for (let i = 0; i < total; i++) {
          const asset = assets[i];
          setEncryptOp({
            status: "running",
            progress: (i + 0.5) / total,
            message: `Encrypting ${i + 1} of ${total}...`,
            error: null,
          });

          const outPath = await encryptImage(asset.uri, passcode, outDir);

          // Verify the encrypted file actually landed on disk before doing
          // anything irreversible to the original — encryptImage()
          // resolving without throwing isn't proof by itself.
          const outInfo = await FileSystem.getInfoAsync(outPath);
          if (!outInfo.exists || outInfo.size === 0) {
            throw new Error(
              `Encrypted output missing or empty for ${asset.fileName ?? asset.uri}`,
            );
          }

          const displayName = buildDisplayName(
            asset.fileName,
            asset.uri,
            new Date(),
          );

          // Best-effort — a failed/missing thumbnail (or color set) must
          // never block the primary encrypt; the grid falls back to the
          // placeholder icon / plain background.
          const { hasThumb, colors } = await generateEncryptedThumbnail(
            asset.uri,
            passcode,
            outPath,
          );

          // Awaited — must not run concurrently; each call does read→modify→write
          // on the index and concurrent calls would overwrite each other. The
          // thumbnail flag and colors are folded into this same call rather
          // than a second index write, for the same reason.
          await vault.recordEncryptedFile(
            outPath,
            albumName ?? null,
            displayName,
            hasThumb,
            colors,
          );

          // Only queued once the encrypted copy is verified on disk *and*
          // durably recorded in the vault index — never before.
          // On Android, deletionRef is the original document Uri (identity
          // resolution for deletion happens natively, inside
          // requestDeleteNative); on iOS it's already a verified assetId
          // (MediaLibrary.getAssetInfoAsync). This is the only place
          // deletion eligibility is decided.
          if (deleteOriginal && asset.deletionRef) {
            assetIdsToDelete.push(asset.deletionRef);
          }
        }

        if (assetIdsToDelete.length > 0) {
          try {
            if (Platform.OS === "android") {
              // DocumentsContract.deleteDocument per Uri first, falling
              // back to MediaStore.createDeleteRequest (one system
              // confirmation dialog for the whole fallback batch) only for
              // Uris that don't support direct deletion. NOT
              // expo-media-library's deleteAssetsAsync — verified by
              // reading its source that it does a raw ContentResolver.delete
              // with no confirmation flow, which reliably fails for media
              // this app didn't create.
              await requestDeleteNative(assetIdsToDelete);
            } else {
              await MediaLibrary.deleteAssetsAsync(assetIdsToDelete);
            }
          } catch {
            // Non-fatal — every encrypted copy is already safely in the
            // vault regardless of whether the OS-level delete succeeded
            // (permission revoked mid-flow, an asset already gone, the
            // user declined the confirmation prompt, etc).
          }
        }

        await vault.logActivity({
          type: "encrypt",
          fileCount: total,
          timestamp: Date.now(),
          detail: albumName ?? undefined,
        });

        setEncryptOp({
          status: "success",
          progress: 1,
          message: `${total} image${total !== 1 ? "s" : ""} encrypted`,
          error: null,
        });
      } catch (e: any) {
        setEncryptOp({
          status: "error",
          progress: 0,
          message: "",
          error: e.message ?? "Encryption failed",
        });
      }
    },
    [vault],
  );

  // ── Decrypt to Photos library ─────────────────────────────────────────────

  const decryptToLibrary = useCallback(
    async (uris: string[], passcode: string) => {
      setDecryptOp({
        status: "running",
        progress: 0,
        message: "Unlocking files...",
        error: null,
      });

      try {
        const { status } = await MediaLibrary.requestPermissionsAsync();
        if (status !== "granted")
          throw new Error("Media library permission denied");

        const cacheDir = FileSystem.cacheDirectory!;
        const total = uris.length;

        for (let i = 0; i < total; i++) {
          setDecryptOp({
            status: "running",
            progress: (i + 0.5) / total,
            message: `Decrypting ${i + 1} of ${total}...`,
            error: null,
          });

          const outPath = await decryptImage(uris[i], passcode, cacheDir);
          await MediaLibrary.saveToLibraryAsync(outPath);
          await FileSystem.deleteAsync(outPath, { idempotent: true });
        }

        await vault.logActivity({
          type: "decrypt",
          fileCount: total,
          timestamp: Date.now(),
        });

        setDecryptOp({
          status: "success",
          progress: 1,
          message: `${total} image${total !== 1 ? "s" : ""} saved to Photos`,
          error: null,
        });
      } catch (e: any) {
        const msg = e.message ?? "";
        const isWrongPasscode =
          msg.includes("padding") || msg.includes("passcode");
        setDecryptOp({
          status: "error",
          progress: 0,
          message: "",
          error: isWrongPasscode ? "Incorrect passcode" : "Decryption failed",
        });
      }
    },
    [vault],
  );

  // ── Secure Camera ────────────────────────────────────────────────────────

  /**
   * Capture a photo via the native camera, encrypt it immediately into the
   * active vault, then delete the temp camera file.
   *
   * The photo is never saved to the device gallery.
   * Returns true if a photo was captured and encrypted, false if the user
   * cancelled or permission was denied.
   */
  const captureAndEncrypt = useCallback(
    async (passcode: string, albumName?: string | null): Promise<boolean> => {
      suppressBackgroundLock();
      let tempUri: string | null;
      try {
        tempUri = await capturePhoto();
      } finally {
        resumeBackgroundLock();
      }
      if (!tempUri) return false;

      setEncryptOp({
        status: "running",
        progress: 0.3,
        message: "Encrypting photo...",
        error: null,
      });

      try {
        const outDir = await vault.ensureAlbumDir(albumName ?? null);
        const outPath = await encryptImage(tempUri, passcode, outDir);

        // Thumbnail + colors are generated from the temp camera file before
        // it's deleted — best-effort, never blocks the primary encrypt.
        const { hasThumb, colors } = await generateEncryptedThumbnail(
          tempUri,
          passcode,
          outPath,
        );

        // Always delete the temp camera file — it must never persist unencrypted
        await FileSystem.deleteAsync(tempUri, { idempotent: true });

        const now = new Date();
        const cameraDisplayName = `Photo ${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, "0")}-${String(now.getDate()).padStart(2, "0")} ${String(now.getHours()).padStart(2, "0")}-${String(now.getMinutes()).padStart(2, "0")}`;

        // Awaited for consistency with encryptImages — index write must complete
        // before we return so the caller's subsequent loadFiles() sees the entry.
        await vault.recordEncryptedFile(
          outPath,
          albumName ?? null,
          cameraDisplayName,
          hasThumb,
          colors,
        );

        await vault.logActivity({
          type: "encrypt",
          fileCount: 1,
          timestamp: Date.now(),
          detail: albumName ?? undefined,
        });

        setEncryptOp({
          status: "success",
          progress: 1,
          message: "Photo encrypted",
          error: null,
        });

        return true;
      } catch (e: any) {
        // Best-effort cleanup on failure — temp file must not linger
        await FileSystem.deleteAsync(tempUri, { idempotent: true });

        setEncryptOp({
          status: "error",
          progress: 0,
          message: "",
          error: e.message ?? "Encryption failed",
        });

        return false;
      }
    },
    [vault],
  );

  const resetEncrypt = useCallback(() => setEncryptOp(idle), []);
  const resetDecrypt = useCallback(() => setDecryptOp(idle), []);

  return {
    encryptOp,
    decryptOp,
    pickImages,
    encryptImages,
    captureAndEncrypt,
    decryptToLibrary,
    resetEncrypt,
    resetDecrypt,
  };
}
